dist: trusty
language: csharp
install: true
mono: none
dotnet: 2.1.507
sudo: required
branches:
  only:
    - master
script:
  - ./build.sh --target=Deploy-CI
env:
  - DeployTo="https://linker-demo.scm.azurewebsites.net/api/zipdeploy"
