image: Visual Studio 2017
branches:
  only:
    - master
environment:
  DeploymentUser: linker-deployer
  DeploymentPassword:
    secure: tSOPikPGEVpvuMYU27Vinw==
test: off
deploy: off
build_script:
  - ps: .\build.ps1 -Target Deploy-WebDeploy
